# Generated by Django 4.0.4 on 2022-08-04 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_rights_request', '0002_datarightsstatus_drprequesttransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DrpRequestTransaction',
        ),
        migrations.RemoveField(
            model_name='datarightsrequest',
            name='request_id',
        ),
    ]
