# Generated by Django 4.0.4 on 2022-08-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rights_request', '0003_delete_drprequesttransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrpRequestTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
