# Generated by Django 3.2.12 on 2022-08-19 17:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_identity', '0005_alter_identityuser_email'),
        ('covered_business', '0009_alter_coveredbusiness_supported_actions'),
        ('data_rights_request', '0004_drprequesttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarightsrequest',
            name='exercise',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('opt_out', 'sale:opt-out'), ('opt_in', 'sale:opt-in'), ('access', 'access'), ('deletion', 'deletion'), ('access_cat', 'access:categories '), ('access_spec', 'access:specific ')], max_length=31), default=list, size=None),
        ),
        migrations.AddField(
            model_name='datarightsrequest',
            name='identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_rights_request.identitypayload'),
        ),
        migrations.AddField(
            model_name='datarightsrequest',
            name='regime',
            field=models.CharField(choices=[('ccpa', 'ccpa'), ('voluntary', 'voluntary')], default='ccpa', max_length=31),
        ),
        migrations.AddField(
            model_name='datarightsrequest',
            name='relationships',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[], max_length=31), default=list, size=None),
        ),
        migrations.AddField(
            model_name='datarightsrequest',
            name='request_id',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='datarightsrequest',
            name='status_callback',
            field=models.URLField(blank=True, default='', max_length=1023),
        ),
        migrations.AddField(
            model_name='datarightsstatus',
            name='expected_by',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='datarightsstatus',
            name='processing_details',
            field=models.TextField(blank=True, default='', max_length=1023),
        ),
        migrations.AddField(
            model_name='datarightsstatus',
            name='reason',
            field=models.TextField(blank=True, choices=[('need_user_verification', 'need_user_verification'), ('suspected_fraud', 'suspected_fraud'), ('insufficient_verification', 'insufficient_verification'), ('no_match', 'no_match'), ('claim_not_covered', 'claim_not_covered'), ('outside_jurisdiction', 'outside_jurisdiction'), ('other', 'other'), ('', '')], default='', max_length=31),
        ),
        migrations.AddField(
            model_name='datarightsstatus',
            name='received_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='datarightsstatus',
            name='request_id',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='datarightsstatus',
            name='results_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='datarightsstatus',
            name='status',
            field=models.TextField(blank=True, choices=[('in_progress', 'in_progress'), ('open', 'open'), ('fulfilled', 'fulfilled'), ('revoked', 'revoked'), ('denied', 'denied'), ('expired', 'expired')], default='', max_length=31),
        ),
        migrations.AddField(
            model_name='drprequesttransaction',
            name='company_id_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covered_business.coveredbusiness'),
        ),
        migrations.AddField(
            model_name='drprequesttransaction',
            name='current_status',
            field=models.TextField(blank=True, choices=[('in_progress', 'in_progress'), ('open', 'open'), ('fulfilled', 'fulfilled'), ('revoked', 'revoked'), ('denied', 'denied'), ('expired', 'expired')], default='', max_length=31),
        ),
        migrations.AddField(
            model_name='drprequesttransaction',
            name='expires_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='drprequesttransaction',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drprequesttransaction',
            name='request_id',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='drprequesttransaction',
            name='user_id_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_identity.identityuser'),
        ),
        migrations.AddField(
            model_name='identitypayload',
            name='address',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='identitypayload',
            name='address_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identitypayload',
            name='audience',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='identitypayload',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='identitypayload',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identitypayload',
            name='issuer',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='identitypayload',
            name='name',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='identitypayload',
            name='phone_number',
            field=models.TextField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='identitypayload',
            name='phone_number_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identitypayload',
            name='power_of_attorney',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='identitypayload',
            name='subject',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
