# Generated by Django 3.2.12 on 2022-08-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rights_request', '0005_auto_20220819_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drprequesttransaction',
            name='expires_date',
            field=models.DateTimeField(null=True),
        ),
    ]
