# Generated by Django 3.2.12 on 2022-08-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rights_request', '0006_alter_drprequesttransaction_expires_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarightsstatus',
            name='expected_by',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='datarightsstatus',
            name='received_at',
            field=models.DateTimeField(null=True),
        ),
    ]
