# Generated by Django 3.2.12 on 2022-08-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_rights_request', '0007_auto_20220819_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarightsstatus',
            name='expected_by',
        ),
        migrations.RemoveField(
            model_name='datarightsstatus',
            name='received_at',
        ),
        migrations.RemoveField(
            model_name='drprequesttransaction',
            name='expires_date',
        ),
    ]
