# Generated by Django 3.2.12 on 2022-08-19 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_rights_request', '0011_auto_20220819_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drprequesttransaction',
            old_name='company_id_ref',
            new_name='company_ref',
        ),
        migrations.RenameField(
            model_name='drprequesttransaction',
            old_name='user_id_ref',
            new_name='user_ref',
        ),
        migrations.CreateModel(
            name='DrpRequestStatusPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_rights_request.datarightsrequest')),
                ('response_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_rights_request.datarightsstatus')),
            ],
        ),
        migrations.AddField(
            model_name='drprequesttransaction',
            name='excer_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_rights_request.drprequeststatuspair'),
        ),
    ]
