# Generated by Django 3.2.12 on 2022-08-24 20:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_rights_request', '0012_auto_20220819_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='drprequesttransaction',
            name='revoke_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revoke_request', to='data_rights_request.drprequeststatuspair'),
        ),
        migrations.AddField(
            model_name='drprequesttransaction',
            name='status_requests',
            field=models.ManyToManyField(to='data_rights_request.DrpRequestStatusPair'),
        ),
        migrations.AlterField(
            model_name='datarightsrequest',
            name='relationships',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=31), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='datarightsstatus',
            name='results_url',
            field=models.URLField(blank=True, default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='drprequesttransaction',
            name='excer_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excer_request', to='data_rights_request.drprequeststatuspair'),
        ),
        migrations.AlterField(
            model_name='identitypayload',
            name='address',
            field=models.EmailField(blank=True, default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='identitypayload',
            name='audience',
            field=models.TextField(blank=True, default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='identitypayload',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='identitypayload',
            name='issuer',
            field=models.TextField(blank=True, default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='identitypayload',
            name='name',
            field=models.TextField(blank=True, default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='identitypayload',
            name='power_of_attorney',
            field=models.EmailField(blank=True, default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='identitypayload',
            name='subject',
            field=models.TextField(blank=True, default='', max_length=127),
        ),
    ]
