# Generated by Django 3.2.12 on 2022-09-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rights_request', '0013_auto_20220824_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarightsstatus',
            name='user_verification_url',
            field=models.URLField(blank=True, default='', max_length=127),
        ),
    ]
