# Generated by Django 3.2.12 on 2022-09-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rights_request', '0014_datarightsstatus_user_verification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarightsstatus',
            name='processing_details',
            field=models.TextField(blank=True, default='', max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='datarightsstatus',
            name='results_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
