# Generated by Django 3.2.12 on 2022-09-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_rights_request', '0016_auto_20220906_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drprequesttransaction',
            name='excer_request',
        ),
        migrations.RemoveField(
            model_name='drprequesttransaction',
            name='revoke_request',
        ),
        migrations.RemoveField(
            model_name='drprequesttransaction',
            name='status_requests',
        ),
    ]
