# Generated by Django 3.2.12 on 2023-04-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rights_request', '0017_auto_20220906_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarightsrequest',
            name='exercise',
        ),
        migrations.AddField(
            model_name='datarightsrequest',
            name='right',
            field=models.CharField(choices=[('opt_out', 'sale:opt-out'), ('opt_in', 'sale:opt-in'), ('access', 'access'), ('deletion', 'deletion'), ('access_cat', 'access:categories '), ('access_spec', 'access:specific ')], default=None, max_length=31),
        ),
    ]
