# Generated by Django 3.2.12 on 2025-01-03 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_rights_request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=63)),
                ('brand_name', models.CharField(blank=True, default='', max_length=63)),
                ('aa_id', models.CharField(blank=True, default='', max_length=63)),
                ('logo', models.ImageField(blank=True, upload_to='company-logos', verbose_name='Logo Image')),
                ('logo_thumbnail', models.ImageField(blank=True, upload_to='company-logos/thumbnails')),
                ('subtitle_description', models.TextField(blank=True)),
                ('verify_key', models.TextField(verbose_name='Base64 encoded key to verify signed requests')),
                ('bearer_token', models.TextField(blank=True, verbose_name='pair-wise token between AA and CB')),
            ],
        ),
        migrations.CreateModel(
            name='DataRightsRequest',
            fields=[
                ('datarightsrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_rights_request.datarightsrequest')),
                ('aa_id', models.CharField(blank=True, default='', max_length=63)),
            ],
            bases=('data_rights_request.datarightsrequest',),
        ),
        migrations.CreateModel(
            name='DataRightsStatus',
            fields=[
                ('datarightsstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_rights_request.datarightsstatus')),
                ('aa_id', models.CharField(blank=True, default='', max_length=63)),
            ],
            bases=('data_rights_request.datarightsstatus',),
        ),
    ]
