# Generated by Django 3.2.12 on 2023-03-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=63)),
                ('brand_name', models.CharField(blank=True, default='', max_length=63)),
                ('aa_id', models.CharField(blank=True, default='', max_length=63)),
                ('logo', models.ImageField(blank=True, upload_to='company-logos', verbose_name='Logo Image')),
                ('logo_thumbnail', models.ImageField(blank=True, upload_to='company-logos/thumbnails')),
                ('subtitle_description', models.TextField(blank=True)),
                ('verify_key', models.TextField(verbose_name='Hex encoded key to verify signed requests')),
            ],
        ),
    ]
