# Generated by Django 3.2.12 on 2023-04-04 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_rights_request', '0017_auto_20220906_1828'),
        ('drp_pip', '0002_authorizedagent_bearer_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRightsRequest',
            fields=[
                ('datarightsrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_rights_request.datarightsrequest')),
            ],
            bases=('data_rights_request.datarightsrequest',),
        ),
        migrations.CreateModel(
            name='DataRightsStatus',
            fields=[
                ('datarightsstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_rights_request.datarightsstatus')),
            ],
            bases=('data_rights_request.datarightsstatus',),
        ),
    ]
