# Generated by Django 3.2.12 on 2023-03-14 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('covered_business', '0001_initial'),
        ('user_identity', '0006_auto_20220901_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(blank=True, choices=[('get-rights', 'get_rights'), ('exercise', 'excercise'), ('get_status', 'get_status')], default='', max_length=10)),
                ('user_first_name', models.CharField(blank=True, default='', max_length=63)),
                ('user_last_name', models.CharField(blank=True, default='', max_length=63)),
                ('covered_biz_name', models.CharField(blank=True, default='', max_length=127)),
                ('is_pip', models.BooleanField(default=False)),
                ('request_action', models.CharField(blank=True, choices=[('access', 'access'), ('deletion', 'deletion')], default='', max_length=10)),
                ('covered_regime', models.CharField(blank=True, choices=[('ccpa', 'ccpa'), ('voluntary', 'voluntary')], default='', max_length=31)),
                ('request_date_time', models.DateTimeField(auto_now=True)),
                ('request_url', models.URLField(blank=True, default='', max_length=127)),
                ('response_code', models.IntegerField(blank=True, default='')),
                ('response_payload', models.CharField(blank=True, default='', max_length=2027)),
                ('is_success', models.BooleanField(default=False)),
                ('covered_biz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covered_business.coveredbusiness')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_identity.identityuser')),
            ],
        ),
    ]
