# Generated by Django 4.0.4 on 2022-05-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=63)),
                ('last_name', models.CharField(blank=True, default='', max_length=63)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('city', models.CharField(blank=True, default='', max_length=63)),
                ('country', models.CharField(blank=True, default='', max_length=63)),
                ('address1', models.CharField(blank=True, default='', max_length=127)),
                ('address2', models.CharField(blank=True, default='', max_length=127)),
                ('state_province', models.CharField(blank=True, default='', max_length=2)),
                ('zip_postal', models.CharField(blank=True, default='', max_length=5)),
            ],
        ),
    ]
