# Generated by Django 4.0.4 on 2022-05-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_identity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityuser',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='identityuser',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='identityuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='identityuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='identityuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='identityuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='identityuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='identityuser',
            name='state_province',
        ),
        migrations.RemoveField(
            model_name='identityuser',
            name='zip_postal',
        ),
    ]
