# Generated by Django 4.0.4 on 2022-05-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_identity', '0002_remove_identityuser_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityuser',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AddField(
            model_name='identityuser',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AddField(
            model_name='identityuser',
            name='city',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
        migrations.AddField(
            model_name='identityuser',
            name='country',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
        migrations.AddField(
            model_name='identityuser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
        migrations.AddField(
            model_name='identityuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
        migrations.AddField(
            model_name='identityuser',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='identityuser',
            name='state_province',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='identityuser',
            name='zip_postal',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
