# Generated by Django 4.0.4 on 2022-05-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_identity', '0003_identityuser_address1_identityuser_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityuser',
            name='email',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
    ]
