# Generated by Django 4.0.4 on 2022-08-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_identity', '0004_identityuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=127),
        ),
    ]
