# Generated by Django 3.2.12 on 2025-01-03 20:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoveredBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=63)),
                ('brand_name', models.CharField(blank=True, default='', max_length=63)),
                ('cb_id', models.CharField(blank=True, default='', max_length=63)),
                ('logo', models.ImageField(blank=True, upload_to='company-logos', verbose_name='Logo Image')),
                ('logo_thumbnail', models.ImageField(blank=True, upload_to='company-logos/thumbnails')),
                ('subtitle_description', models.TextField(blank=True)),
                ('discovery_endpoint', models.URLField(blank=True, default='', max_length=127)),
                ('api_root_endpoint', models.URLField(blank=True, default='', max_length=127)),
                ('supported_actions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('opt_out', 'sale:opt-out'), ('opt_in', 'sale:opt-in'), ('access', 'access'), ('deletion', 'deletion'), ('access_cat', 'access:categories '), ('access_spec', 'access:specific ')], max_length=31), default=list, size=None)),
                ('auth_bearer_token', models.CharField(blank=True, default='', max_length=4096)),
            ],
        ),
    ]
