# Generated by Django 3.2.12 on 2025-03-20 19:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveredbusiness',
            name='supported_verifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('address', 'address'), ('email', 'email'), ('phone', 'phone')], max_length=31), default=list, size=None),
        ),
    ]
