# Generated by Django 4.0.4 on 2022-05-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_business', '0002_coveredbusiness_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveredbusiness',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
        migrations.AddField(
            model_name='coveredbusiness',
            name='name',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
    ]
