# Generated by Django 4.0.4 on 2022-05-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_business', '0001_initial'),
    ]

    operations = [
    ]
