# Generated by Django 4.0.4 on 2022-05-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_business', '0004_remove_coveredbusiness_is_internal_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveredbusiness',
            name='delete_data_details',
        ),
        migrations.RemoveField(
            model_name='coveredbusiness',
            name='opt_out_details',
        ),
        migrations.RemoveField(
            model_name='coveredbusiness',
            name='request_description',
        ),
        migrations.RemoveField(
            model_name='coveredbusiness',
            name='request_email',
        ),
        migrations.AddField(
            model_name='coveredbusiness',
            name='api_endpoint',
            field=models.URLField(blank=True, default='', max_length=127),
        ),
    ]
