# Generated by Django 4.0.4 on 2022-06-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_business', '0005_remove_coveredbusiness_delete_data_details_and_more'),
    ]

    operations = [
    ]
