# Generated by Django 4.0.4 on 2022-08-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_business', '0006_coveredbusiness_api_secret_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coveredbusiness',
            old_name='api_endpoint',
            new_name='api_root_endpoint',
        ),
        migrations.AddField(
            model_name='coveredbusiness',
            name='discovery_endpoint',
            field=models.URLField(blank=True, default='', max_length=127),
        ),
    ]
