# Generated by Django 3.2.12 on 2022-08-19 17:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_business', '0008_coveredbusiness_supported_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveredbusiness',
            name='supported_actions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('opt_out', 'sale:opt-out'), ('opt_in', 'sale:opt-in'), ('access', 'access'), ('deletion', 'deletion'), ('access_cat', 'access:categories '), ('access_spec', 'access:specific ')], max_length=31), default=list, size=None),
        ),
    ]
