# Generated by Django 3.2.12 on 2022-12-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_business', '0010_resize_auth_bearer_token'),
    ]

    operations = [
    ]
