# Generated by Django 3.2.12 on 2023-02-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_business', '0010_resize_auth_bearer_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveredbusiness',
            name='decode_api_secret',
            field=models.BooleanField(default=False),
        ),
    ]
