# Generated by Django 3.2.12 on 2023-01-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_business', '0011_coveredbusiness_cb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveredbusiness',
            name='status_callback',
            field=models.URLField(blank=True, default='', max_length=127),
        ),
    ]
