# Generated by Django 3.2.12 on 2023-01-11 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covered_business', '0012_coveredbusiness_status_callback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveredbusiness',
            name='status_callback',
        ),
    ]
