# Generated by Django 3.2.12 on 2023-03-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covered_business', '0002_auto_20230327_2039'),
        ('covered_business', '0013_remove_coveredbusiness_status_callback'),
    ]

    operations = [
    ]
