# Generated by Django 3.2.12 on 2023-03-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covered_business', '0014_merge_20230330_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveredbusiness',
            name='api_secret',
        ),
        migrations.RemoveField(
            model_name='coveredbusiness',
            name='signing_key',
        ),
        migrations.RemoveField(
            model_name='coveredbusiness',
            name='verify_key',
        ),
    ]
