
# Generated by Django 3.2.12 on 2023-03-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covered_business', '0015_auto_20230330_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveredbusiness',
            name='decode_api_secret',
        ),
    ]
