# Generated by Django 3.2.12 on 2023-04-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_business', '0018_remove_coveredbusiness_api_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveredbusiness',
            name='business_contact',
            field=models.TextField(blank=True, verbose_name='Email address to contact for business/legal communiques'),
        ),
        migrations.AddField(
            model_name='coveredbusiness',
            name='technical_contact',
            field=models.TextField(blank=True, verbose_name='Email address to contact for technical issues'),
        ),
        migrations.AddField(
            model_name='coveredbusiness',
            name='web_url',
            field=models.TextField(blank=True, verbose_name="Business's home page"),
        ),
    ]
